# nisan.taslak.site — port 8083
# Konum: /etc/nginx/sites-available/nisan.taslak.site
# ln -s /etc/nginx/sites-available/nisan.taslak.site /etc/nginx/sites-enabled/

server {
    listen 8083;
    listen [::]:8083;
    server_name nisan.taslak.site;

    root  /var/www/davetiye;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(jpeg|jpg|mp3|png|ico|webp)$ {
        expires     30d;
        add_header  Cache-Control "public, immutable";
    }

    add_header X-Frame-Options       SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
}
